### ISSUE TITLE
any way to make it to do the opposite?

### ISSUE THREAD

**Issue by vt-idiot** [Nekupaska/BlacklistEmojisBBDD#1]
This seems to hide emojis in messages and reactions, is there any way to make it do the opposite? Hide them in auto-complete results or in the emote picker?

**Comment by vt-idiot** [comment]
Well, I found a klutzy way to make it hide them in the picker...
```js
function processEmotes(changes) {
    let emotes = document.querySelectorAll("button[data-type='emoji'],button[data-type='sticker'],img[data-type='emoji'],img[data-type='sticker']"); //use changes from observer(changes) instead, search there
...
function hideElement(em) {
    //em.style.opacity = 0; //hide emote
    em.remove();
}
```

**Comment by Nekupaska** [comment]
> Well, I found a klutzy way to make it hide them in the picker...
> ```js
> function processEmotes(changes) {
>     let emotes = document.querySelectorAll("button[data-type='emoji'],button[data-type='sticker'],img[data-type='emoji'],img[data-type='sticker']"); //use changes from observer(changes) instead, search there
> ...
> function hideElement(em) {
>     //em.style.opacity = 0; //hide emote
>     em.remove();
> }
> ```

Hey, as long as it works
